функции для генерации контента
htmlacademy-javascript/535549-kekstagram-28 pull request #3
Opened 2023-02-21 18:31 UTC by evgen66rus

4.16. Больше деталей

2023-02-22 13:31 UTC, Spearance requested changes

2023-02-22 13:31 UTC, Spearance commented on js/main.js
> +// console.log(makeId);
в пул реквест не должны попадать закомментированные консоли и фрагменты кода

2023-02-22 13:31 UTC, Spearance commented on js/main.js
> +const makeId = Array.from({length: 25}, (_, i) => i + 1);
25 нужно сохранить в константу

2023-02-22 13:31 UTC, Spearance commented on js/main.js
> +  for (let i = 1; i <= 25; i++) {
если бы была сохраненная константа, то не понадобилось бы писать абстрактное число, в критериях это называется "магическое значение"

2023-02-22 13:31 UTC, Spearance commented on js/main.js
> +
в целом по коду, слишком много одинаковых циклов, это подпадает под критерий, можно всё сделать за 1-2

2023-03-11 11:12 UTC, evgen66rus commented on js/main.js
> +
не знаю как этого сделать ((
как по мне, дак все они разные..

2023-03-11 14:58 UTC, merged